// <copyright file=Strings.Designer.cs
// <copyright>
//  Copyright (c) 2016, University of Stuttgart
//  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the Software),
//  to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
//  and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//  The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//  THE SOFTWARE IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
//  DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
//  OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// </copyright>
// <license>MIT License</license>
// <main contributors>
//  Markus Funk, Thomas Kosch, Sven Mayer
// </main contributors>
// <co-contributors>
//  Paul Brombosch, Mai El-Komy, Juana Heusler, 
//  Matthias Hoppe, Robert Konrad, Alexander Martin
// </co-contributors>
// <patent information>
//  We are aware that this software implements patterns and ideas,
//  which might be protected by patents in your country.
//  Example patents in Germany are:
//      Patent reference number: DE 103 20 557.8
//      Patent reference number: DE 10 2013 220 107.9
//  Please make sure when using this software not to violate any existing patents in your country.
// </patent information>
// <date> 11/2/2016 12:25:59 PM</date>

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace motionEAPAdmin.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("motionEAPAdmin.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string buttonAudio {
            get {
                return ResourceManager.GetString("buttonAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string buttonCancel {
            get {
                return ResourceManager.GetString("buttonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        public static string buttonCircle {
            get {
                return ResourceManager.GetString("buttonCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause / Continue.
        /// </summary>
        public static string buttonContinueRecording {
            get {
                return ResourceManager.GetString("buttonContinueRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string buttonDelete {
            get {
                return ResourceManager.GetString("buttonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect all.
        /// </summary>
        public static string buttonDeselectAll {
            get {
                return ResourceManager.GetString("buttonDeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect zone.
        /// </summary>
        public static string buttonDetectZone {
            get {
                return ResourceManager.GetString("buttonDetectZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string buttonDown {
            get {
                return ResourceManager.GetString("buttonDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string buttonFilter {
            get {
                return ResourceManager.GetString("buttonFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find ID.
        /// </summary>
        public static string buttonFindID {
            get {
                return ResourceManager.GetString("buttonFindID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string buttonImage {
            get {
                return ResourceManager.GetString("buttonImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string buttonLoad {
            get {
                return ResourceManager.GetString("buttonLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load assembly zone.
        /// </summary>
        public static string buttonLoadAssemblyZone {
            get {
                return ResourceManager.GetString("buttonLoadAssemblyZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load box layout.
        /// </summary>
        public static string buttonLoadBoxLayout {
            get {
                return ResourceManager.GetString("buttonLoadBoxLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load detection zone layout.
        /// </summary>
        public static string buttonLoadDetectionZoneLayout {
            get {
                return ResourceManager.GetString("buttonLoadDetectionZoneLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load object zone.
        /// </summary>
        public static string buttonLoadObjectZone {
            get {
                return ResourceManager.GetString("buttonLoadObjectZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load scene.
        /// </summary>
        public static string buttonLoadScene {
            get {
                return ResourceManager.GetString("buttonLoadScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New scene.
        /// </summary>
        public static string buttonNewScene {
            get {
                return ResourceManager.GetString("buttonNewScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play 2D record.
        /// </summary>
        public static string buttonPlay2DRecord {
            get {
                return ResourceManager.GetString("buttonPlay2DRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play 3D record.
        /// </summary>
        public static string buttonPlay3DRecord {
            get {
                return ResourceManager.GetString("buttonPlay3DRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygon.
        /// </summary>
        public static string buttonPolygon {
            get {
                return ResourceManager.GetString("buttonPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit assembly.
        /// </summary>
        public static string buttonQuitAssembly {
            get {
                return ResourceManager.GetString("buttonQuitAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record 2D gesture.
        /// </summary>
        public static string buttonRecord2DGesture {
            get {
                return ResourceManager.GetString("buttonRecord2DGesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record 3D gesture.
        /// </summary>
        public static string buttonRecord3DGesture {
            get {
                return ResourceManager.GetString("buttonRecord3DGesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record 3D profile.
        /// </summary>
        public static string buttonRecord3DProfile {
            get {
                return ResourceManager.GetString("buttonRecord3DProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        public static string buttonRectangle {
            get {
                return ResourceManager.GetString("buttonRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string buttonRemove {
            get {
                return ResourceManager.GetString("buttonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        public static string buttonRotation {
            get {
                return ResourceManager.GetString("buttonRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string buttonSave {
            get {
                return ResourceManager.GetString("buttonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save assembly zone.
        /// </summary>
        public static string buttonSaveAssemblyZone {
            get {
                return ResourceManager.GetString("buttonSaveAssemblyZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save box layout.
        /// </summary>
        public static string buttonSaveBoxLayout {
            get {
                return ResourceManager.GetString("buttonSaveBoxLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save detection zone layout.
        /// </summary>
        public static string buttonSaveDetectionZoneLayout {
            get {
                return ResourceManager.GetString("buttonSaveDetectionZoneLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save scene.
        /// </summary>
        public static string buttonSaveScene {
            get {
                return ResourceManager.GetString("buttonSaveScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan object.
        /// </summary>
        public static string buttonScanObjects {
            get {
                return ResourceManager.GetString("buttonScanObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot.
        /// </summary>
        public static string buttonScreenshot {
            get {
                return ResourceManager.GetString("buttonScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string buttonSelectAll {
            get {
                return ResourceManager.GetString("buttonSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot.
        /// </summary>
        public static string buttonSnapshot {
            get {
                return ResourceManager.GetString("buttonSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start assembly.
        /// </summary>
        public static string buttonStartAssembly {
            get {
                return ResourceManager.GetString("buttonStartAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start recording.
        /// </summary>
        public static string buttonStartRecording {
            get {
                return ResourceManager.GetString("buttonStartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start recording video.
        /// </summary>
        public static string buttonStartRecordingVideo {
            get {
                return ResourceManager.GetString("buttonStartRecordingVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop recording.
        /// </summary>
        public static string buttonStopRecording {
            get {
                return ResourceManager.GetString("buttonStopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop recording video.
        /// </summary>
        public static string buttonStopRecordingVideo {
            get {
                return ResourceManager.GetString("buttonStopRecordingVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string buttonText {
            get {
                return ResourceManager.GetString("buttonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text viewer.
        /// </summary>
        public static string buttonTextViewer {
            get {
                return ResourceManager.GetString("buttonTextViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string buttonUp {
            get {
                return ResourceManager.GetString("buttonUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string buttonVideo {
            get {
                return ResourceManager.GetString("buttonVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable automatic Adaptivity.
        /// </summary>
        public static string checkboxAdaptivityEnabled {
            get {
                return ResourceManager.GetString("checkboxAdaptivityEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display visual feedback.
        /// </summary>
        public static string checkboxDisplayVisualFeedback {
            get {
                return ResourceManager.GetString("checkboxDisplayVisualFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable edit mode?.
        /// </summary>
        public static string checkboxEnableEditMode {
            get {
                return ResourceManager.GetString("checkboxEnableEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Ensenso Smoothing.
        /// </summary>
        public static string checkboxEnableEnsensoSmoothing {
            get {
                return ResourceManager.GetString("checkboxEnableEnsensoSmoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable box fault detection.
        /// </summary>
        public static string checkboxEnableFaultDetection {
            get {
                return ResourceManager.GetString("checkboxEnableFaultDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable gesture mapping?.
        /// </summary>
        public static string checkboxEnableGestureMapping {
            get {
                return ResourceManager.GetString("checkboxEnableGestureMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free space.
        /// </summary>
        public static string checkboxFreeSpace {
            get {
                return ResourceManager.GetString("checkboxFreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert display?.
        /// </summary>
        public static string checkboxInvertDisplay {
            get {
                return ResourceManager.GetString("checkboxInvertDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop play.
        /// </summary>
        public static string checkboxLoopPlay2DRecord {
            get {
                return ResourceManager.GetString("checkboxLoopPlay2DRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop play.
        /// </summary>
        public static string checkboxLoopPlay3DRecord {
            get {
                return ResourceManager.GetString("checkboxLoopPlay3DRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object mapping.
        /// </summary>
        public static string checkboxObjectMapping {
            get {
                return ResourceManager.GetString("checkboxObjectMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project visual feedback.
        /// </summary>
        public static string checkboxProjectVisualFeedback {
            get {
                return ResourceManager.GetString("checkboxProjectVisualFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognize objects.
        /// </summary>
        public static string checkboxRecognizeObjects {
            get {
                return ResourceManager.GetString("checkboxRecognizeObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show criticals.
        /// </summary>
        public static string checkboxShowCriticals {
            get {
                return ResourceManager.GetString("checkboxShowCriticals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show demo animation?.
        /// </summary>
        public static string checkboxShowDemoAnimation {
            get {
                return ResourceManager.GetString("checkboxShowDemoAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show errors.
        /// </summary>
        public static string checkboxShowErrors {
            get {
                return ResourceManager.GetString("checkboxShowErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show FPS on screen?.
        /// </summary>
        public static string checkboxShowFPSOnScreen {
            get {
                return ResourceManager.GetString("checkboxShowFPSOnScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show informations.
        /// </summary>
        public static string checkboxShowInformations {
            get {
                return ResourceManager.GetString("checkboxShowInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show warnings.
        /// </summary>
        public static string checkboxShowWarnings {
            get {
                return ResourceManager.GetString("checkboxShowWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start projection.
        /// </summary>
        public static string checkboxStartProjection {
            get {
                return ResourceManager.GetString("checkboxStartProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream scenedata via UDP to IP.
        /// </summary>
        public static string checkboxStreamUDP {
            get {
                return ResourceManager.GetString("checkboxStreamUDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track object.
        /// </summary>
        public static string checkboxTrackObject {
            get {
                return ResourceManager.GetString("checkboxTrackObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string labelActions {
            get {
                return ResourceManager.GetString("labelActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaptivity Threshold to Hard.
        /// </summary>
        public static string labelAdaptivityThresholdHard {
            get {
                return ResourceManager.GetString("labelAdaptivityThresholdHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaptivity Threshold to Medium.
        /// </summary>
        public static string labelAdaptivityThresholdMedium {
            get {
                return ResourceManager.GetString("labelAdaptivityThresholdMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box feedback timeout.
        /// </summary>
        public static string labelBoxFeedbackTimeout {
            get {
                return ResourceManager.GetString("labelBoxFeedbackTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorframe offset X:.
        /// </summary>
        public static string labelColorframeOffsetX {
            get {
                return ResourceManager.GetString("labelColorframeOffsetX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorframe offset Y:.
        /// </summary>
        public static string labelColorframeOffsetY {
            get {
                return ResourceManager.GetString("labelColorframeOffsetY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of Rectangle.
        /// </summary>
        public static string labelCountOfRectangle {
            get {
                return ResourceManager.GetString("labelCountOfRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current step.
        /// </summary>
        public static string labelCurrentStep {
            get {
                return ResourceManager.GetString("labelCurrentStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DepthRange.
        /// </summary>
        public static string labelDepthRange {
            get {
                return ResourceManager.GetString("labelDepthRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string labelDescription {
            get {
                return ResourceManager.GetString("labelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detection mode.
        /// </summary>
        public static string labelDetectionMode {
            get {
                return ResourceManager.GetString("labelDetectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestures.
        /// </summary>
        public static string labelGestures {
            get {
                return ResourceManager.GetString("labelGestures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string labelHeight {
            get {
                return ResourceManager.GetString("labelHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert.
        /// </summary>
        public static string labelInvert {
            get {
                return ResourceManager.GetString("labelInvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded workflow.
        /// </summary>
        public static string labelLoadedWorkflow {
            get {
                return ResourceManager.GetString("labelLoadedWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching tolerance:.
        /// </summary>
        public static string labelMatchingTolerance {
            get {
                return ResourceManager.GetString("labelMatchingTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximal depth.
        /// </summary>
        public static string labelMaxDepth {
            get {
                return ResourceManager.GetString("labelMaxDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinArea (onAdding):.
        /// </summary>
        public static string labelMinAreaonAdding {
            get {
                return ResourceManager.GetString("labelMinAreaonAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinArea (Subtraction):.
        /// </summary>
        public static string labelMinAreaSubtraction {
            get {
                return ResourceManager.GetString("labelMinAreaSubtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal depth.
        /// </summary>
        public static string labelMinDepth {
            get {
                return ResourceManager.GetString("labelMinDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinValueChange (add):.
        /// </summary>
        public static string labelMinValueChangeAdd {
            get {
                return ResourceManager.GetString("labelMinValueChangeAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinValueChange (sub):.
        /// </summary>
        public static string labelMinValueChangeSub {
            get {
                return ResourceManager.GetString("labelMinValueChangeSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving Threshold.
        /// </summary>
        public static string labelMovingThreshold {
            get {
                return ResourceManager.GetString("labelMovingThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string labelName {
            get {
                return ResourceManager.GetString("labelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of work step.
        /// </summary>
        public static string labelNameOfWorkStep {
            get {
                return ResourceManager.GetString("labelNameOfWorkStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth Token.
        /// </summary>
        public static string labelNetworkAuthToken {
            get {
                return ResourceManager.GetString("labelNetworkAuthToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Settings.
        /// </summary>
        public static string labelNetworkSettings {
            get {
                return ResourceManager.GetString("labelNetworkSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name.
        /// </summary>
        public static string labelNetworkTableName {
            get {
                return ResourceManager.GetString("labelNetworkTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string labelNext {
            get {
                return ResourceManager.GetString("labelNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recognition.
        /// </summary>
        public static string labelNoRecognition {
            get {
                return ResourceManager.GetString("labelNoRecognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not playing.
        /// </summary>
        public static string labelNotPlaying2DRecord {
            get {
                return ResourceManager.GetString("labelNotPlaying2DRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Playing.
        /// </summary>
        public static string labelNotPlaying3DRecord {
            get {
                return ResourceManager.GetString("labelNotPlaying3DRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not recording 2D.
        /// </summary>
        public static string labelNotRecording2D {
            get {
                return ResourceManager.GetString("labelNotRecording2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not recording 3D.
        /// </summary>
        public static string labelNotRecording3D {
            get {
                return ResourceManager.GetString("labelNotRecording3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not recording profile.
        /// </summary>
        public static string labelNotRecordingProfile {
            get {
                return ResourceManager.GetString("labelNotRecordingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No workflow loaded.
        /// </summary>
        public static string labelNoWorkflowLoaded {
            get {
                return ResourceManager.GetString("labelNoWorkflowLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        public static string labelOffset {
            get {
                return ResourceManager.GetString("labelOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parts produced.
        /// </summary>
        public static string labelPartsProduced {
            get {
                return ResourceManager.GetString("labelPartsProduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to save image to:.
        /// </summary>
        public static string labelPathToSaveImageTo {
            get {
                return ResourceManager.GetString("labelPathToSaveImageTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of pixels to match:.
        /// </summary>
        public static string labelPercentOfPixelMatch {
            get {
                return ResourceManager.GetString("labelPercentOfPixelMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % to Trigger.
        /// </summary>
        public static string labelPercentWithinBoundTrigger {
            get {
                return ResourceManager.GetString("labelPercentWithinBoundTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string labelPrevious {
            get {
                return ResourceManager.GetString("labelPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server base address.
        /// </summary>
        public static string labelServerBaseAddress {
            get {
                return ResourceManager.GetString("labelServerBaseAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string labelSettingsHeight {
            get {
                return ResourceManager.GetString("labelSettingsHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoothing.
        /// </summary>
        public static string labelSmoothing {
            get {
                return ResourceManager.GetString("labelSmoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoothing Steps.
        /// </summary>
        public static string labelSmoothingSteps {
            get {
                return ResourceManager.GetString("labelSmoothingSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string labelStatus {
            get {
                return ResourceManager.GetString("labelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping Threshold.
        /// </summary>
        public static string labelStoppingThreshold {
            get {
                return ResourceManager.GetString("labelStoppingThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time:.
        /// </summary>
        public static string labelTimeEnd {
            get {
                return ResourceManager.GetString("labelTimeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Span:.
        /// </summary>
        public static string labelTimeSpan {
            get {
                return ResourceManager.GetString("labelTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time:.
        /// </summary>
        public static string labelTimeStart {
            get {
                return ResourceManager.GetString("labelTimeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string labelWidth {
            get {
                return ResourceManager.GetString("labelWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work steps:.
        /// </summary>
        public static string labelWorkSteps {
            get {
                return ResourceManager.GetString("labelWorkSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string listViewGroup {
            get {
                return ResourceManager.GetString("listViewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string listViewID {
            get {
                return ResourceManager.GetString("listViewID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string listViewImage {
            get {
                return ResourceManager.GetString("listViewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string listViewMessage {
            get {
                return ResourceManager.GetString("listViewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string listViewPath {
            get {
                return ResourceManager.GetString("listViewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string menuItemAbout {
            get {
                return ResourceManager.GetString("menuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrate Kinect....
        /// </summary>
        public static string menuItemCalibrateKinect {
            get {
                return ResourceManager.GetString("menuItemCalibrateKinect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrate Table....
        /// </summary>
        public static string menuItemCalibrateTable {
            get {
                return ResourceManager.GetString("menuItemCalibrateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string menuItemClose {
            get {
                return ResourceManager.GetString("menuItemClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string menuItemDelete {
            get {
                return ResourceManager.GetString("menuItemDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string menuItemEdit {
            get {
                return ResourceManager.GetString("menuItemEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Custom Scene.
        /// </summary>
        public static string menuItemEditCustomScene {
            get {
                return ResourceManager.GetString("menuItemEditCustomScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Scene.
        /// </summary>
        public static string menuItemEditScene {
            get {
                return ResourceManager.GetString("menuItemEditScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit Workflow.
        /// </summary>
        public static string menuItemEditWorkflow {
            get {
                return ResourceManager.GetString("menuItemEditWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string menuItemEnglish {
            get {
                return ResourceManager.GetString("menuItemEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string menuItemExit {
            get {
                return ResourceManager.GetString("menuItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string menuItemFile {
            get {
                return ResourceManager.GetString("menuItemFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string menuItemGerman {
            get {
                return ResourceManager.GetString("menuItemGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string menuItemHelp {
            get {
                return ResourceManager.GetString("menuItemHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string menuItemLanguage {
            get {
                return ResourceManager.GetString("menuItemLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load scene.
        /// </summary>
        public static string menuItemLoadScene {
            get {
                return ResourceManager.GetString("menuItemLoadScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Load Workflow.
        /// </summary>
        public static string menuItemLoadWorkflow {
            get {
                return ResourceManager.GetString("menuItemLoadWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Scene.
        /// </summary>
        public static string menuItemNewScene {
            get {
                return ResourceManager.GetString("menuItemNewScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New Workflow.
        /// </summary>
        public static string menuItemNewWorkflow {
            get {
                return ResourceManager.GetString("menuItemNewWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string menuItemOptions {
            get {
                return ResourceManager.GetString("menuItemOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string menuItemSave {
            get {
                return ResourceManager.GetString("menuItemSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Scene.
        /// </summary>
        public static string menuItemSaveScene {
            get {
                return ResourceManager.GetString("menuItemSaveScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenes.
        /// </summary>
        public static string menuItemScenes {
            get {
                return ResourceManager.GetString("menuItemScenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        public static string menuItemSettings {
            get {
                return ResourceManager.GetString("menuItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly area.
        /// </summary>
        public static string radioButtonAssemblyArea {
            get {
                return ResourceManager.GetString("radioButtonAssemblyArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob.
        /// </summary>
        public static string radioButtonBlob {
            get {
                return ResourceManager.GetString("radioButtonBlob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contour.
        /// </summary>
        public static string radioButtonContour {
            get {
                return ResourceManager.GetString("radioButtonContour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing area.
        /// </summary>
        public static string radioButtonDrawingArea {
            get {
                return ResourceManager.GetString("radioButtonDrawingArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string radioButtonOn {
            get {
                return ResourceManager.GetString("radioButtonOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan  table.
        /// </summary>
        public static string radioButtonScanTable {
            get {
                return ResourceManager.GetString("radioButtonScanTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static.
        /// </summary>
        public static string radioButtonStatic {
            get {
                return ResourceManager.GetString("radioButtonStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2DTouch.
        /// </summary>
        public static string tabItem2DTouch {
            get {
                return ResourceManager.GetString("tabItem2DTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly zone.
        /// </summary>
        public static string tabItemAssemblyZone {
            get {
                return ResourceManager.GetString("tabItemAssemblyZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxes.
        /// </summary>
        public static string tabItemBoxes {
            get {
                return ResourceManager.GetString("tabItemBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string tabItemDebug {
            get {
                return ResourceManager.GetString("tabItemDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string tabItemEditor {
            get {
                return ResourceManager.GetString("tabItemEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestures.
        /// </summary>
        public static string tabItemGestures {
            get {
                return ResourceManager.GetString("tabItemGestures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestures Debug.
        /// </summary>
        public static string tabItemGesturesDebug {
            get {
                return ResourceManager.GetString("tabItemGesturesDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects.
        /// </summary>
        public static string tabItemObjects {
            get {
                return ResourceManager.GetString("tabItemObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PBD.
        /// </summary>
        public static string tabItemPBD {
            get {
                return ResourceManager.GetString("tabItemPBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenes.
        /// </summary>
        public static string tabItemScenes {
            get {
                return ResourceManager.GetString("tabItemScenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string tabItemSettings {
            get {
                return ResourceManager.GetString("tabItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey.
        /// </summary>
        public static string tabItemSurvey {
            get {
                return ResourceManager.GetString("tabItemSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string tabItemVideo {
            get {
                return ResourceManager.GetString("tabItemVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualization.
        /// </summary>
        public static string tabItemVisualization {
            get {
                return ResourceManager.GetString("tabItemVisualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow.
        /// </summary>
        public static string tabItemWorkflow {
            get {
                return ResourceManager.GetString("tabItemWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration.
        /// </summary>
        public static string titleCalibrationDialog {
            get {
                return ResourceManager.GetString("titleCalibrationDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Workflow.
        /// </summary>
        public static string titleCreateWorkflowDialog {
            get {
                return ResourceManager.GetString("titleCreateWorkflowDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string titleSettingsWindow {
            get {
                return ResourceManager.GetString("titleSettingsWindow", resourceCulture);
            }
        }
    }
}
